### ISSUE TITLE
Remove unused `core-js` dependency

### ISSUE THREAD

**Issue by griga** [lukas-reining/eventsource#1]
The `eventsource` repository currently lists `core-js` as a dependency, but it seems to be unused throughout the codebase. I suggest removing this dependency to streamline the project.

**Comment by lukas-reining** [comment]
Hey @griga, thanks for opening the issue.
Moved it to the dev dependencies, as you are right that the dependency is already bundled and does not need to be installed with the package.
Version 1.4.1 fixes that :)
