### ISSUE TITLE
`extended-eventsource` writes directly to stdout (and this behavior isn't configurable)

### ISSUE THREAD

**Issue by mkantor** [lukas-reining/eventsource#10]
In [several](https://github.com/lukas-reining/eventsource/blob/bb4492023174b9cda86dc1d1551f935475082c87/src/eventsource.ts#L194) [places](https://github.com/lukas-reining/eventsource/blob/bb4492023174b9cda86dc1d1551f935475082c87/src/eventsource.ts#L146) this package uses `console` methods to write directly to standard output. This can be problematic when used from a CLI program where I want to have full control over my program's output. Currently I'm seeing messages like `Connection established` in my output which I have no straightforward way of preventing.

Would you consider accepting a pull request which removes all usages of `console.*`? Or if not, perhaps a new [option](https://github.com/lukas-reining/eventsource/blob/bb4492023174b9cda86dc1d1551f935475082c87/src/eventsource.ts#L5-L8) to allow some mechanism to disable them?

**Comment by lukas-reining** [comment]
Hey @mkantor,
thank you for the feedback and creating the issue!
I would not disable logging by default as the native EventSource depends on logs as the only real interface for runtime information. This is the part of the spec that describes this: 

https://html.spec.whatwg.org/multipage/server-sent-events.html#implementation-advice
> Implementations are especially encouraged to report detailed information to their development consoles whenever an [error](https://html.spec.whatwg.org/multipage/indices.html#event-error) event is fired, since little to no information can be made available in the events themselves.
[https://html.spec.whatwg.org/multipage/server-sent-events.html#implementation-advice]
 
I just published a [new version (1.4.6)](https://www.npmjs.com/package/extended-eventsource/v/1.4.6) that has an option called `disableLogger`.
Also you can define a custom logger and provide it via the `logger` option.

Please leave feedback if this change helps!

**Comment by lukas-reining** [comment]
I just realized, that you offered to create a PR.
If you have anything else or additional to this and want to do it yourself, you are more than welcome to create a PR :) 
Thank you!

**Comment by mkantor** [comment]
No worries, the changes you made look great to me. Thanks for the speedy response!
