### ISSUE TITLE
EventSouce error on using fetch function

### ISSUE THREAD

**Issue by leofred** [lukas-reining/eventsource#14]
The application cant connect to SSE

Steps to Reproduce:

Install version 1.5.0.
Run the application.

Expected Behavior:

The application connect to SSE server.

Actual Behavior:

The application doesn't create the connection.

Screenshots/Logs:

![image](https://github.com/user-attachments/assets/121d82b3-8360-4647-bde5-72e71bb34e74)

Error occurred in EventSource TypeError: Failed to execute 'fetch' on 'Window': Illegal invocation

Environment:

Version: 1.5.0
Node Version: v20.11.1

Additional Context:

The issue started after upgrading from 1.4.9 to 1.5.0. Rolling back to 1.4.9 resolves the problem.

**Comment by lukas-reining** [comment]
Hey @leofred, I pushed a fix for it, please check it out.
