### ISSUE TITLE
Empty string as the first response data

### ISSUE THREAD

**Issue by Power-Howdy** [lukas-reining/eventsource#2]
Thanks for creating such a wonderful package,  @lukas-reining 
I was trying to use sse in my angular app, but couldn't set Authorization header for request, and I found this package, really helpful.
By the way, why does it send **empty string "" as the first data**?
Of course, this is not a big issue, but as I was trying to send json string from backend and parse it on frontend, I encountered this, which caught me for some time.
Of course I added validation logic to avoid error, but I just want this package to be perfect.

**Comment by lukas-reining** [comment]
Hey, thanks for the feedback!
I will have a look later to check this!
Could you please give me some information on how you are sending the server sent events? Like which library and so @Power-Howdy?

**Comment by lukas-reining** [comment]
Hey @Power-Howdy,
I found one possibility where an empty string could be dispatched, which is when a comment is sent and then a NewLine.
Not sure if this was your problem. I published version 1.4.2 which fixes this.
Maybe you can give me some info on how you are sending the events and how exactly you are consuming them. I could imagine an extra NewLine in the beginning that leads to the empty string.
Please let me know if 1.4.2 fixes your problem :)

**Comment by Power-Howdy** [comment]
> Hey @Power-Howdy, I found one possibility where an empty string could be dispatched, which is when a comment is sent and then a NewLine. Not sure if this was your problem. I published version 1.4.2 which fixes this. Maybe you can give me some info on how you are sending the events and how exactly you are consuming them. I could imagine an extra NewLine in the beginning that leads to the empty string. Please let me know if 1.4.2 fixes your problem :)

New version solved the problem, thanks

**Comment by cvazac** [comment]
For anyone who stumbles upon this later, I'm seeing empty messages in the browser when I incorrectly provide a second newline to my keep-alive comment.

This is correct: 
```
// Node.js
response.write(": keep-alive\n");
```

**Comment by lukas-reining** [comment]
Hey @cvazac, thanks for the information!
Just as an additional information:

This is intended behavior, the spec specifies where a message ends, and an additional line break ends an empty message: 
https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation

The problem for @Power-Howdy was, that comment messages were also parsed, while they should not be interpreted at all. 

I cannot see in the spec, that a message must not be empty, and the section I linked seems also does not mention it. But if I am interpreting it wrong, I would be happy to fix it :)
