### ISSUE TITLE
Confusing warnings when retrying with disableRetry set to true

### ISSUE THREAD

**Issue by CakeWithDivinity** [lukas-reining/eventsource#4]
When setting `disableRetry` to `true` in the config and an event happens that would trigger a retry, the library still logs a warning to the console, although the retry will not happen due to the `disableRetry` option in the config.
This is a bit confusing. The warning tells the developer it will reconnect to the event-source, while actually not doing so.

I think it should not log the warning in this case. Or is this expected behaviour?

https://github.com/lukas-reining/eventsource/blob/ad8eb89b52cf6ae98338638af91faf6ceb20b247/src/eventsource.ts#L146C1-L153C1

**Comment by lukas-reining** [comment]
Hey @CakeWithDivinity, yes this log message was confusing in the case `disableRetry` was set to false.
I changed this in version 1.4.3 that I just published. Please leave feedback if this behaves more like you expect now!
Thanks for the feedback!

**Comment by CakeWithDivinity** [comment]
Yes, this should make it a lot less confusing. Thank you for the quick fix.
