### ISSUE TITLE
Is it normal that onmessage never fires?

### ISSUE THREAD

**Issue by prewk** [lukas-reining/eventsource#8]
I can do this:

```ts
eventSource.addEventListener('specific-event-type', msg => { ... });
```

And it'll fire, but

```ts
eventSource.onmessage = msg => { .... }
```

Will never fire.

**Comment by lukas-reining** [comment]
Mh it should @prewk.
Important to know is that onmessage will only fire when the event type is message. This is compliant to the behavior of the original eventsource. It will never fire for `specific-event-type`.
Does it work for you if the event type is message?

**Comment by lukas-reining** [comment]
You can see it here @prewk: https://developer.mozilla.org/en-US/docs/Web/API/EventSource/message_event#syntax
Please let me know if it is working this way for you. If there is no event type but just data it should also fire, as `message` is the default type.

**Comment by prewk** [comment]
Thanks for informing me!
