### ISSUE TITLE
Detecting http error statuses

### ISSUE THREAD

**Issue by prewk** [lukas-reining/eventsource#9]
How would I extract an 401 from the event in `onerror`?

**Comment by lukas-reining** [comment]
Hey @prewk, right now this is not possible.
The default interface of the Event class does not allow for additional information.
We could add a custom event type or maybe even a custom error handler.
I can try to do this in the next days, or If you like you could also give it a try.

**Comment by prewk** [comment]
Thanks! I don't have time to contribute right now but we'll see.
